# Excercise 6.1

## Data Cleaning and Consistency Checks

In [5]:
# importing libaries
import pandas as pd
import numpy as np
import os

In [7]:
# creatng path
path = r'C:\Users\jeffr\Documents\Medical Costs Analysis'

In [9]:
# importing insurance data set
df_Insur = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'insurance.csv'), index_col = False)

In [13]:
df_Insur.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [21]:
#checking datat types
df_Insur.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [23]:
# checking for mixed data types
for col in df_Insur.columns.tolist():
    weird = (df_Insur[[col]].map(type) != df_Insur[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (df_Insur[weird]) > 0:
        print(col)

In [25]:
# checking for missing values
df_Insur.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [41]:
# checking for duplicate rows
df_Insur.duplicated().sum()

1

In [43]:
df_Insur[df_Insur.duplicated()]

     age   sex    bmi  children smoker     region    charges
581   19  male  30.59         0     no  northwest  1639.5631

In [45]:
df_Insur.drop_duplicates(inplace=True)

In [47]:
df_Insur.duplicated().sum()

0

In [27]:
df_Insur.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [53]:
df_Insur.describe()

               age          bmi     children       charges
count  1337.000000  1337.000000  1337.000000   1337.000000
mean     39.222139    30.663452     1.095737  13279.121487
std      14.044333     6.100468     1.205571  12110.359656
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.290000     0.000000   4746.344000
50%      39.000000    30.400000     1.000000   9386.161300
75%      51.000000    34.700000     2.000000  16657.717450
max      64.000000    53.130000     5.000000  63770.428010

In [49]:
df_Insur.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   object
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   object
 5   region    1337 non-null   object
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 83.6+ KB

In [51]:
# exporting data set
df_Insur.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'insurance.csv'))